config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :create ]
  end
  resources :reviews, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, presence: true
  validates :category, presence: true, inclusion: { in: %w{ chinese italian japanese french belgian } }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/show"
    end
  end

    def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1 class="pb-3">Restaurant List</h1>
  <ul class="list-group pb-5">
    <% @restaurants.each do |restaurant| %>
      <li class="list-group-item py-4"></i><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <% end %>
  </ul>
  <%= link_to "Create a new restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h1>Create a new Restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: "Enter your restaurant name" %>
  <%= f.input :address, label: "Enter your restaurant's address" %>
  <%= f.input :category, label: "Enter your restaurant's category" %>
  <%= f.submit "Create new restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <h2 class="pb-5"><%= @restaurant.name %></h2>
  <div class="card bg-grey text-dark">
    <div class="card-body"><%= @restaurant.address %></div>
  </div>
  <% if @restaurant.reviews %>
      <ul class="list-group">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item"><%= review.content %>   Rating:<%= review.rating %></li>
              <%= link_to "Remove",
                  review_path(review),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
        <% end %>
      </ul>
    <%else %>
    <p class="py-5"><i class="far fa-square"></i>No reviews yet</p>
  <%end %>

  <div>
  <button type="button" class="btn btn-info mb-5"><%= link_to "Back to list of restaurants", restaurants_path %></button>
  </div>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |

  <%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>